### ISSUE TITLE
APP各項色碼及對應規則

### ISSUE THREAD

**Issue by mapleegg** [ProjectWmega/ios-app#5]
### 綜合項目：
主標題 `#323333`
逐三小時折線圖、溫度折線圖、雨量直方圖 `#323333`
子標題 `#9FA0A0`
底色色碼 `#EEEEEF`

### 溫度相關項目：
逐三小時溫度、現在溫度

0°C ![#344E67](https://placehold.it/15/344E67/000000?text=+)  `#344E67`(52,78,103)
1°C ![#32506C](https://placehold.it/15/32506C/000000?text=+) `#32506C`(50,80,108)
2°C ![#305272](https://placehold.it/15/305272/000000?text=+) `#305272`(48,82,114)
3°C ![#2E5377](https://placehold.it/15/2E5377/000000?text=+) `#2E5377`(46,83,119)
4°C ![#2C557D](https://placehold.it/15/2C557D/000000?text=+) `#2C557D`(44,85,125)
5°C ![#2A5782](https://placehold.it/15/2A5782/000000?text=+) `#2A5782`(42,87,130)
6°C ![#285987](https://placehold.it/15/285987/000000?text=+) `#285987`(40,89,135)
7°C ![#265B8D](https://placehold.it/15/265B8D/000000?text=+) `#265B8D`(38,91,141)
8°C ![#286296](https://placehold.it/15/286296/000000?text=+) `#286296`(40,98,150)
9°C ![#2D6DA1](https://placehold.it/15/2D6DA1/000000?text=+) `#2D6DA1`(45,109,161)
10°C ![#3277AC](https://placehold.it/15/3277AC/000000?text=+) `#3277AC`(50,119,172)
11°C ![#3781B7](https://placehold.it/15/3781B7/000000?text=+) `#3781B7`(55,129,183)
12°C ![#3C8BC2](https://placehold.it/15/3C8BC2/000000?text=+) `#3C8BC2`(60,139,194)
13°C ![#4195CD](https://placehold.it/15/4195CD/000000?text=+) `#4195CD`(65,149,205)
14°C ![#459FD8](https://placehold.it/15/459FD8/000000?text=+) `#459FD8`(69,159,216)
15°C ![#4AA9E1](https://placehold.it/15/4AA9E1/000000?text=+) `#4AA9E1`(74,169,225)
16°C ![#52ADD0](https://placehold.it/15/52ADD0/000000?text=+) `#52ADD0`(82,173,208)
17°C ![#59B1C0](https://placehold.it/15/59B1C0/000000?text=+) `#59B1C0`(89,177,192)
18°C ![#61B5AF](https://placehold.it/15/61B5AF/000000?text=+) `#61B5AF`(97,181,175)
19°C ![#69B99E](https://placehold.it/15/69B99E/000000?text=+) `#69B99E`(105,185,158)
20°C ![#7FC284](https://placehold.it/15/7FC284/000000?text=+) `#7FC284`(127,194,132)
21°C ![#93CA6C](https://placehold.it/15/93CA6C/000000?text=+) `#93CA6C`(147,202,108)
22°C ![#A9D352](https://placehold.it/15/A9D352/000000?text=+) `#A9D352`(169,211,82)
23°C ![#BFDB38](https://placehold.it/15/BFDB38/000000?text=+) `#BFDB38`(191,219,56)
24°C ![#D1D51D](https://placehold.it/15/D1D51D/000000?text=+) `#D1D51D`(209,213,29)
25°C ![#E3CE01](https://placehold.it/15/E3CE01/000000?text=+) `#E3CE01`(227,206,1)
26°C ![#E0B30B](https://placehold.it/15/E0B30B/000000?text=+) `#E0B30B`(224,179,11)
27°C ![#DB9517](https://placehold.it/15/DB9517/000000?text=+) `#DB9517`(219,149,23)
28°C ![#D47A28](https://placehold.it/15/D47A28/000000?text=+) `#D47A28`(212,122,40)
29°C ![#CB623C](https://placehold.it/15/CB623C/000000?text=+) `#CB623C`(203,98,60)
30°C ![#C24D4A](https://placehold.it/15/C24D4A/000000?text=+) `#C24D4A`(194,77,74)
31°C ![#BC4547](https://placehold.it/15/BC4547/000000?text=+) `#BC4547`(188,69,71)
32°C ![#B63E43](https://placehold.it/15/B63E43/000000?text=+) `#B63E43`(182,62,67)
33°C ![#B03640](https://placehold.it/15/B03640/000000?text=+) `#B03640`(176,54,64)
34°C ![#AA2E3D](https://placehold.it/15/AA2E3D/000000?text=+) `#AA2E3D`(170,46,61)
35°C ![#A42E43](https://placehold.it/15/A42E43/000000?text=+) `#A42E43`(164,46,67)
36°C ![#9F3251](https://placehold.it/15/9F3251/000000?text=+)  `#9F3251`(159,50,81)
37°C ![#9A3760](https://placehold.it/15/9A3760/000000?text=+)  `#9A3760`(154,55,96)
38°C ![#953C6E](https://placehold.it/15/953C6E/000000?text=+)  `#953C6E`(149,60,110)
39°C ![#90407C](https://placehold.it/15/90407C/000000?text=+)  `#90407C`(144,64,124)
40°C ![#8D4385](https://placehold.it/15/8D4385/000000?text=+)  `#8D4385`(141,67,133)

一週溫度曲線色碼

高溫 ![#E5963C](https://placehold.it/15/E5963C/000000?text=+) `#E5963C`
低溫 ![#64B8E2](https://placehold.it/15/64B8E2/000000?text=+) `#64B8E2`

### 空氣相關項目：

級距
維護中 ![#595757](https://placehold.it/15/595757/000000?text=+)  `#595757`
優異 ![#64B8E2](https://placehold.it/15/64B8E2/000000?text=+)  `#64B8E2`
良好 ![#4FB99F](https://placehold.it/15/4FB99F/000000?text=+)  `#4FB99F`
普通 ![#F0C419](https://placehold.it/15/F0C419/000000?text=+)  `#F0C419`
稍差![#D9881D](https://placehold.it/15/D9881D/000000?text=+)  `#D9881D`
不良 ![#C44F4B](https://placehold.it/15/C44F4B/000000?text=+)  `#C44F4B`
非常不良 ![#8D5385](https://placehold.it/15/8D5385/000000?text=+)  `#8D5385`
危害 ![#925C57](https://placehold.it/15/925C57/000000?text=+)  `#925C57`

排名三角形
上升 ![#4FB99F](https://placehold.it/15/4FB99F/000000?text=+)  `#4FB99F`
下降 ![#C44F4B](https://placehold.it/15/C44F4B/000000?text=+)  `#C44F4B`

**Comment by osk2** [comment]
幫 @mapleegg 視覺化色碼

**Comment by mapleegg** [comment]
@osk2 謝謝你，太棒了！
